version: "3.8"


x-backend-services: &backend-service
  # Common options for backend services
  build: backend
  volumes:
    - downloads:/downloads/
    - ./backend:/app/src
  environment:
    - REDIS_PORT=6379
    - REDIS_HOST=redis


services:

  frontend:
    build: frontend
    ports:
      - 24678:24678
    volumes:
      - ./frontend:/app/src

  backend:
    <<: *backend-service

  celery:
    <<: *backend-service
    command: celery -A clipchimp.tasks worker -l info

  redis:
    image: redis:5

  nginx:
    build: nginx
    ports:
      - 8000:80
    volumes:
      - downloads:/downloads/


volumes:
  downloads:
