version: "3.8"


services:

  backend:
    build: backend
    volumes:
      - downloads:/downloads/

  redis:
    image: redis:5

  nginx:
    image: nginx:1.23
    ports:
      - 8000:8000
    volumes:
      - downloads:/downloads/


volumes:
  downloads:
