version: "3.8"


x-backend-service: &backend-service
  build: backend
  environment:
    - REDIS_PORT=6379
    - REDIS_HOST=redis
  volumes:
    - downloads:/downloads


services:
  frontend:
    ports:
      - 24678:24678
    build: frontend
    environment:
      - BACKEND_URL=http://localhost:8000
      - TRUFFLE_API_KEY=${TRUFFLE_API_KEY}

  backend:
    <<: *backend-service

  celery:  
    <<: *backend-service
    command: celery -A clipchimp.tasks worker -l info

  redis:
    image: redis:5

  nginx:
    build: nginx
    ports:
      - 8000:80
    volumes:
      - downloads:/downloads
    environment:
      - BACKEND_HOST=backend
      - FRONTEND_HOST=frontend
      - PUBLIC_HOST=${PUBLIC_HOST:-clipchimp.jerbob.me}


volumes:
  downloads:
