version: "3.8"


x-backend-service: &backend-service
  environment:
    - REDIS_PORT=6379
    - REDIS_HOST=redis


services:
  frontend:
    ports:
      - 24678:24678
    image: ghcr.io/jerbob/clipchimp-frontend:latest
    environment:
      - TRUFFLE_API_KEY=${TRUFFLE_API_KEY}

  backend:
    <<: *backend-service
    image: ghcr.io/jerbob/clipchimp:latest
    volumes:
      - downloads:/downloads

  celery:  
    <<: *backend-service
    image: ghcr.io/jerbob/clipchimp:latest
    command: celery -A clipchimp.tasks worker -l info
    volumes:
      - downloads:/downloads

  redis:
    image: redis:5

  nginx:
    build: nginx
    ports:
      - 8000:80
    volumes:
      - downloads:/downloads
    environment:
      - BACKEND_HOST=backend
      - FRONTEND_HOST=frontend
      - PUBLIC_HOST=${PUBLIC_HOST:-clipchimp.jerbob.me}

  watchtower:
    image: docker.io/containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 5


volumes:
  downloads:
