name: Build and publish to GHCR

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build container
      run: docker build -t ghcr.io/jerbob/clipchimp:${GITHUB_SHA} -t ghcr.io/jerbob/clipchimp:latest backend

    - name: Login to GHCR
      run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u jerbob --password-stdin

    - name: Push to GHCR
      run: |
          docker push ghcr.io/jerbob/clipchimp:${GITHUB_SHA}
          docker push ghcr.io/jerbob/clipchimp:latest
